function c = dysts_catalog(manifestPath)
%DYSTS_CATALOG The dysts systems, as catalogue entries the battery understands.
%
%   c = quarctest.dysts_catalog()
%   c = quarctest.dysts_catalog(path_to_manifest_json)
%
%   Returns a struct array with the same fields quarctest.sprott_catalog
%   supplies, so quarctest.embed_policy and quarctest.metric_policy apply to
%   these systems unchanged and the two catalogues can be reported together.
%
%   PROVENANCE. The systems come from the database of Gilpin (2021), which
%   carries for each one a Lyapunov spectrum computed by integrating the
%   tangent space with Gram-Schmidt/QR orthonormalization and a correlation
%   dimension. Both are obtained from the linearized equations rather than from
%   a time series, which is the same standing Sprott's Appendix A values have
%   and the reason these systems can be used as references at all.
%
%   The series themselves are generated by python/export_dysts.py, using the
%   same code that produced the published exponents, and read from disk here.
%   Nothing in this file integrates anything: c.file names the binary holding
%   that system's ensemble.
%
%   WHAT DIFFERS FROM THE SPROTT ENTRIES. There is no d2_err, because dysts
%   states no uncertainty on its correlation dimensions, so a comparison
%   against them cannot be made against a published error bar the way Sprott's
%   can. Every entry is a flow. tier is "numerical" throughout: none of these
%   exponents is a closed form.
%
%   See also QUARCTEST.SPROTT_CATALOG, QUARCTEST.CHARACTERIZE_SERIES.

% Copyright (c) 2021-2026 Quantitative Analysis Research Core,
% Center for Human Movement Variability, University of Nebraska at Omaha.
% MIT licence. See LICENSE.txt.

arguments
    manifestPath (1,1) string = ""
end

if manifestPath == ""
    here = fileparts(fileparts(fileparts(mfilename('fullpath'))));   % tests/
    manifestPath = fullfile(here, 'reports', 'dysts', 'manifest.json');
end
if ~isfile(manifestPath)
    error('quarctest:dystsCatalog:noManifest', ...
        ['No dysts manifest at %s. Generate one with\n' ...
         '  python/export_dysts.py --out tests/reports/dysts --R 100 --N 4000'], ...
        manifestPath);
end

m = jsondecode(fileread(manifestPath));
S = m.systems;
if ~iscell(S), S = num2cell(S); end

root = fileparts(manifestPath);
c = struct('name', {}, 'pretty', {}, 'section', {}, 'category', {}, ...
           'kind', {}, 'f', {}, 'x0', {}, 'lambda', {}, 'tier', {}, ...
           'obs', {}, 'dt', {}, 'usable', {}, 'note', {}, ...
           'd2', {}, 'd2_err', {}, 'file', {}, 'fs', {}, 'R', {}, 'N', {}, ...
           'dtype', {}, 'source', {});

for i = 1:numel(S)
    e = S{i};
    d2 = NaN;
    if isfield(e, 'corrDim') && ~isempty(e.corrDim) && isnumeric(e.corrDim)
        d2 = double(e.corrDim);
    end
    cat = "dysts_flow";
    if isfield(e, 'hamiltonian') && e.hamiltonian
        cat = "dysts_conservative_flow";
    elseif isfield(e, 'nonautonomous') && e.nonautonomous
        cat = "dysts_driven_flow";
    end

    s = struct( ...
        'name',     string(e.system), ...
        'pretty',   string(e.system), ...
        'section',  "dysts", ...
        'category', cat, ...
        'kind',     "flow", ...
        'f',        [], ...                       % series come from disk
        'x0',       zeros(double(e.stateDim), 1), ...  % width only: embed_policy
        'lambda',   double(e.lambdaMax), ...
        'tier',     "numerical", ...
        'obs',      double(e.obsIndex) + 1, ...   % python is 0-based
        'dt',       double(e.dt), ...
        'usable',   true, ...
        'note',     "", ...
        'd2',       d2, ...
        'd2_err',   NaN, ...
        'file',     string(fullfile(root, e.file)), ...
        'fs',       double(e.fs), ...
        'R',        double(e.R), ...
        'N',        double(e.N), ...
        'dtype',    localDtype(e), ...
        'source',   "dysts");
    c(end+1) = s; %#ok<AGROW>
end
end

% ---------------------------------------------------------------- internals

function d = localDtype(e)
%LOCALDTYPE Storage type of the exported series, defaulting to the old format.
%   Manifests written before the switch to float64 carry no dtype field.
if isfield(e, 'dtype') && ~isempty(e.dtype)
    d = char(string(e.dtype));
else
    d = 'float32';
end
end
