function paths = write_characterization(S, per, opts)
%WRITE_CHARACTERIZATION Write the characterization report to disk.
%
%   paths = quarctest.write_characterization(S)
%   paths = quarctest.write_characterization(S, per)
%   paths = quarctest.write_characterization(S, per, OutDir=d, Tag=t)
%
%   S    summary table from quarctest.characterize
%   per  optional per-realization table from the same call
%
%   Writes, into tests/reports by default:
%     characterization.csv    the summary table, one row per system and metric
%     characterization.md     the same content as a readable report
%     characterization_per_realization.csv  written only when per is given
%
%   THE REPORT IS THE DELIVERABLE. This suite does not pass or fail; it
%   produces a record of how every estimator in the library behaved on every
%   system in the catalogue, with the spread across an ensemble of initial
%   conditions and, for the two quantities Sprott publishes, the reference and
%   its stated uncertainty. Committing that record is what makes the
%   comparison over time possible: the question "did this change anything" is
%   answered by diffing two reports and looking, not by a threshold.
%
%   It goes in tests/reports rather than tests/artifacts because artifacts is
%   gitignored scratch for the pass/fail suite, and this is meant to be kept.
%
%   The markdown groups by system and marks every row as characterized or
%   validated. A validated row is one where Sprott publishes a value; there
%   are exactly two such metrics, the largest Lyapunov exponent and the
%   correlation dimension. Every other row is a measurement of this library's
%   estimator on this system and is not a claim about correctness.
%
%   See also QUARCTEST.CHARACTERIZE, QUARCTEST.WRITE_SPROTT_MARKDOWN.

% Copyright (c) 2021-2026 Quantitative Analysis Research Core,
% Center for Human Movement Variability, University of Nebraska at Omaha.
% MIT licence. See LICENSE.txt.

arguments
    S   table
    per table = table()
    opts.OutDir (1,1) string = ""
    opts.Tag    (1,1) string = ""
end

if opts.OutDir == ""
    here = fileparts(fileparts(fileparts(mfilename('fullpath'))));  % tests/
    outDir = fullfile(here, 'reports');
else
    outDir = char(opts.OutDir);
end
if ~exist(outDir, 'dir'), mkdir(outDir); end

stem = "characterization";
if opts.Tag ~= "", stem = stem + "_" + opts.Tag; end

csvPath = fullfile(outDir, char(stem + ".csv"));
mdPath  = fullfile(outDir, char(stem + ".md"));
writetable(S, csvPath);

paths = struct('csv', string(csvPath), 'md', string(mdPath), 'per', "");

if ~isempty(per)
    perPath = fullfile(outDir, char(stem + "_per_realization.csv"));
    writetable(per, perPath);
    paths.per = string(perPath);
end

fid = fopen(mdPath, 'w');
c = onCleanup(@() fclose(fid));

N = S.N(1); R = S.R(1); seed = S.seed(1); spread = S.spread(1);
systems = unique(S.system, 'stable');

fprintf(fid, '# Metric characterization across Sprott (2003) Appendix A\n\n');
fprintf(fid, 'Generated by `quarctest.characterize`. Regenerate with:\n\n');
fprintf(fid, '```\nmatlab -batch "addpath(''tests/matlab''); ');
fprintf(fid, '[S,p] = quarctest.characterize(R=%d, N=%d); ', R, N);
fprintf(fid, 'quarctest.write_characterization(S,p)"\n```\n\n');

fprintf(fid, '## What this is\n\n');
fprintf(fid, ['For every system, %d initial conditions are drawn i.i.d. around the published\n' ...
              'one (Sprott''s own x0 is always realization 1), a series of %d samples is\n' ...
              'generated from each, and the full metric battery is run on it. The tables below\n' ...
              'report the distribution of each metric across that ensemble.\n\n'], R, N);
fprintf(fid, ['**Nothing here passes or fails.** Sprott publishes two of these quantities, the\n' ...
              'largest Lyapunov exponent and the correlation dimension, and rows for those are\n' ...
              'marked `validated` and carry the reference with its published uncertainty where\n' ...
              'he states one. Every other row is marked `characterized`: it is a measurement of\n' ...
              'this library''s estimator on this system, and no reference value exists to judge\n' ...
              'it against. Inventing a tolerance for those would be a number with no provenance\n' ...
              'presented as a criterion.\n\n']);

fprintf(fid, '## Protocol\n\n');
fprintf(fid, '| parameter | value |\n|---|---|\n');
fprintf(fid, '| realizations per system | %d |\n', R);
fprintf(fid, '| samples per realization | %d |\n', N);
fprintf(fid, '| IC draw | x0 + %g * max(abs(x0),1) * randn, i.i.d. |\n', spread);
fprintf(fid, '| base seed | %d |\n', seed);
fprintf(fid, '| realization 1 | the published x0, verbatim |\n');
fprintf(fid, '| sampling | decimation fixed per system from the published x0 |\n');
fprintf(fid, '| embedding, maps | delay 1, dimension = state dimension + 1 |\n');
fprintf(fid, '| embedding, flows | delay from `ami`, dimension from `fnn`, per realization |\n');
fprintf(fid, '| spread statistic | MAD about the median, unscaled |\n\n');

fprintf(fid, ['The embedding rule differs by kind on purpose. A map''s iterates are its natural\n' ...
              'coordinates, so its delay is 1 by construction and AMI''s first minimum is not an\n' ...
              'embedding delay at all; a flow observed through one variable has a genuinely\n' ...
              'unknown embedding, estimated here the way a user would estimate it. `ami_delay`\n' ...
              'and `fnn_dim` are reported for both, alongside the `embed_delay` and `embed_dim`\n' ...
              'actually used, so the difference is visible rather than buried.\n\n']);

% ---- systems that did not deliver a full ensemble
lost = [];
for i = 1:numel(systems)
    r1 = S(S.system == systems(i), :);
    if r1.usableRealizations(1) < R
        lost(end+1) = i; %#ok<AGROW>
    end
end
if ~isempty(lost)
    fprintf(fid, '## Systems with an incomplete ensemble\n\n');
    fprintf(fid, ['A realization is dropped when its series is degenerate -- the orbit collapsed,\n' ...
                  'diverged, or produced an observable that is not bounded and recurrent. Where\n' ...
                  'the loss is large, **the surviving realizations are a sample conditioned on\n' ...
                  'not degenerating**, and the spread reported for that system describes a\n' ...
                  'narrower quantity than it does elsewhere. Read those rows accordingly.\n\n']);
    fprintf(fid, '| system | category | usable | of |\n|---|---|---|---|\n');
    for k = lost
        r1 = S(S.system == systems(k), :);
        fprintf(fid, '| `%s` | %s | %d | %d |\n', systems(k), r1.category(1), ...
                r1.usableRealizations(1), R);
    end
    fprintf(fid, ['\nThree of these -- `damped_pendulum`, `driven_pendulum` and `labyrinth` --\n' ...
                  'degenerate from Sprott''s own initial condition, before any perturbation. Their\n' ...
                  'observable carries an unbounded drift, and delay embedding requires a bounded\n' ...
                  'recurrent observable, so no sampling scheme recovers them. They are the same\n' ...
                  'three systems the Lyapunov benchmark returns NaN for.\n\n']);
end

for i = 1:numel(systems)
    sysName = systems(i);
    rows = S(S.system == sysName, :);
    fprintf(fid, '## %s (%s, %s)\n\n', sysName, rows.section(1), rows.category(1));
    fprintf(fid, 'Usable realizations: %d of %d. fs = %g.\n\n', ...
            rows.usableRealizations(1), R, rows.fs(1));

    fprintf(fid, '| metric | role | n | median | MAD | mean | SD | reference | ratio |\n');
    fprintf(fid, '|---|---|---|---|---|---|---|---|---|\n');
    for k = 1:height(rows)
        r = rows(k,:);
        if r.role == "excluded"
            fprintf(fid, '| `%s` | excluded | - | - | - | - | - | - | - |\n', r.metric);
            continue
        end
        role = "characterized";
        refStr = "-";
        if r.referenceStatus == "published"
            role = "validated";
            if isfinite(r.referenceUncertainty) && r.referenceUncertainty > 0
                refStr = sprintf("%.4g +/- %.3g", r.reference, r.referenceUncertainty);
            else
                refStr = sprintf("%.4g", r.reference);
            end
        end
        ratioStr = "-";
        if isfinite(r.medianOverReference)
            ratioStr = sprintf("%.3f", r.medianOverReference);
        end
        fprintf(fid, '| `%s` | %s | %d | %.4g | %.3g | %.4g | %.3g | %s | %s |\n', ...
                r.metric, role, r.n, r.median, r.mad, r.mean, r.sd, refStr, ratioStr);
    end
    fprintf(fid, '\n');

    ex = rows(rows.role == "excluded", :);
    if height(ex) > 0
        fprintf(fid, 'Excluded here: ');
        seen = unique(ex.excludedBecause);
        for j = 1:numel(seen)
            names = ex.metric(ex.excludedBecause == seen(j));
            fprintf(fid, '%s -- %s. ', strjoin("`" + names + "`", ", "), seen(j));
        end
        fprintf(fid, '\n\n');
    end
end
end
